name: deploy

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.pull_request.merged == true

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: setup node
        run: |
          npm ci
          npm install gulp -g
      - name: gulp build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public_html


